# Generated by Django 5.2.5 on 2025-11-09 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assemblies', '0009_alter_assembly_solved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoincidentConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('point1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point1_coincidentconstraint', to='assemblies.assemblypoint')),
                ('point2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point2_coincidentconstraint', to='assemblies.assemblypoint')),
            ],
            bases=('constraints.constraint',),
        ),
    ]
