# Generated by Django 5.2.5 on 2025-11-16 12:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assemblies', '0001_initial'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(editable=False, max_length=50)),
                ('is_explicit', models.BooleanField(default=False, editable=False)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_constraint', to='assemblies.assembly')),
            ],
        ),
        migrations.CreateModel(
            name='AngleConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('value', models.FloatField(help_text='Degrees')),
                ('angle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angle_angleconstraint', to='references.referenceangle')),
            ],
            bases=('constraints.constraint',),
        ),
        migrations.CreateModel(
            name='CoincidentConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('reference1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference1_coincidentconstraint', to='references.reference')),
                ('reference2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference2_coincidentconstraint', to='references.reference')),
            ],
            bases=('constraints.constraint',),
        ),
        migrations.CreateModel(
            name='DistanceConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('value', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_distanceconstraint', to='references.referenceline')),
            ],
            bases=('constraints.constraint',),
        ),
        migrations.CreateModel(
            name='ParallelConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('line1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line1_parallelconstraint', to='references.referenceline')),
                ('line2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line2_parallelconstraint', to='references.referenceline')),
            ],
            bases=('constraints.constraint',),
        ),
        migrations.CreateModel(
            name='PerpendicularConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('line1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line1_perpendicularconstraint', to='references.referenceline')),
                ('line2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line2_perpendicularconstraint', to='references.referenceline')),
            ],
            bases=('constraints.constraint',),
        ),
        migrations.CreateModel(
            name='VariableAngleConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('minimum', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('maximum', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('angle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angle_variableangleconstraint', to='references.referenceangle')),
            ],
            bases=('constraints.constraint',),
        ),
        migrations.CreateModel(
            name='VariableDistanceConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('minimum', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('maximum', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_variabledistanceconstraint', to='references.referenceline')),
            ],
            bases=('constraints.constraint',),
        ),
    ]
