# Generated by Django 5.2.5 on 2025-11-09 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0009_alter_assembly_solved'),
        ('constraints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='assembly',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assembly_constraint', to='assemblies.assembly'),
            preserve_default=False,
        ),
    ]
