# Generated by Django 5.2.5 on 2025-11-09 02:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0009_alter_assembly_solved'),
        ('constraints', '0002_constraint_assembly'),
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('point1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point1_distanceconstraint', to='assemblies.assemblypoint')),
                ('point2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point2_distanceconstraint', to='assemblies.assemblypoint')),
            ],
            bases=('constraints.constraint',),
        ),
    ]
