# Generated by Django 5.2.5 on 2025-12-06 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0002_remove_constraint_is_explicit'),
        ('references', '0006_remove_reference_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedPointConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_fixedpointconstraint', to='references.referencepoint', unique=True)),
            ],
            bases=('constraints.constraint',),
        ),
    ]
