# Generated by Django 5.2.5 on 2025-11-09 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0003_distanceconstraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
