# Generated by Django 5.2.5 on 2025-12-06 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0003_fixedpointconstraint'),
        ('references', '0006_remove_reference_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedpointconstraint',
            name='point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='point_fixedpointconstraint', to='references.referencepoint'),
        ),
    ]
