# Generated by Django 5.2.5 on 2025-12-06 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0004_alter_fixedpointconstraint_point'),
        ('references', '0006_remove_reference_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointPointCoincidentConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('point1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point1_pointpointcoincidentconstraint', to='references.referencepoint')),
                ('point2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point2_pointpointcoincidentconstraint', to='references.referencepoint')),
            ],
            bases=('constraints.constraint',),
        ),
        migrations.DeleteModel(
            name='CoincidentConstraint',
        ),
    ]
