# Generated by Django 5.2.5 on 2025-11-09 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0004_alter_constraint_type'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distanceconstraint',
            name='point1',
        ),
        migrations.RemoveField(
            model_name='distanceconstraint',
            name='point2',
        ),
        migrations.AddField(
            model_name='distanceconstraint',
            name='line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='line_distanceconstraint', to='references.referenceline'),
            preserve_default=False,
        ),
    ]
