# Generated by Django 5.2.5 on 2025-11-09 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0005_remove_distanceconstraint_point1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AngleConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('value', models.FloatField(help_text='Degrees')),
            ],
            bases=('constraints.constraint',),
        ),
        migrations.RenameField(
            model_name='distanceconstraint',
            old_name='distance',
            new_name='value',
        ),
    ]
