# Generated by Django 5.2.5 on 2025-12-06 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0005_pointpointcoincidentconstraint_and_more'),
        ('references', '0006_remove_reference_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointLineCoincidentConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_pointlinecoincidentconstraint', to='references.referenceline')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_pointlinecoincidentconstraint', to='references.reference')),
            ],
            bases=('constraints.constraint',),
        ),
    ]
