# Generated by Django 5.2.5 on 2025-11-09 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0006_angleconstraint_and_more'),
        ('references', '0002_reference_remove_referenceline_assembly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='angleconstraint',
            name='angle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angle_angleconstraint', to='references.referenceangle'),
        ),
    ]
