# Generated by Django 5.2.5 on 2025-12-06 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0006_pointlinecoincidentconstraint'),
        ('references', '0006_remove_reference_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointlinecoincidentconstraint',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_pointlinecoincidentconstraint', to='references.referencepoint'),
        ),
    ]
