# Generated by Django 5.2.5 on 2026-01-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0007_alter_pointlinecoincidentconstraint_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedpointconstraint',
            name='x_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedpointconstraint',
            name='y_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
