# Generated by Django 5.2.5 on 2025-11-10 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0007_angleconstraint_angle'),
        ('references', '0003_alter_reference_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParallelConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('line1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line1_parallelconstraint', to='references.referenceline')),
                ('line2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line2_parallelconstraint', to='references.referenceline')),
            ],
            bases=('constraints.constraint',),
        ),
    ]
