# Generated by Django 5.2.5 on 2025-11-10 09:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0009_perpendicularconstraint'),
        ('references', '0003_alter_reference_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableAngleConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('minimum', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('maximum', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('angle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='angle_variableangleconstraint', to='references.referenceangle')),
            ],
            bases=('constraints.constraint',),
        ),
        migrations.CreateModel(
            name='VariableDistanceConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('minimum', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('maximum', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_variabledistanceconstraint', to='references.referenceline')),
            ],
            bases=('constraints.constraint',),
        ),
    ]
