# Generated by Django 5.2.5 on 2025-11-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0010_variableangleconstraint_variabledistanceconstraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constraint',
            name='type',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
