# Generated by Django 5.2.5 on 2025-11-11 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0011_assembly_status'),
        ('constraints', '0011_alter_constraint_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericCoincidentConstraint',
            fields=[
                ('constraint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='constraints.constraint')),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('point1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point1_genericcoincidentconstraint', to='assemblies.assemblypoint')),
            ],
            bases=('constraints.constraint',),
        ),
    ]
