# Generated by Django 5.2.5 on 2025-11-11 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0012_genericcoincidentconstraint'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericcoincidentconstraint',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ['assemblypoint', 'referenceline']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
