# Generated by Django 5.2.5 on 2025-11-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0013_alter_genericcoincidentconstraint_content_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericCoincidentConstraint',
        ),
    ]
