# Generated by Django 5.2.5 on 2025-11-11 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0014_delete_genericcoincidentconstraint'),
        ('references', '0005_alter_referenceline_point1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coincidentconstraint',
            name='point1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point1_coincidentconstraint', to='references.referencepoint'),
        ),
        migrations.AlterField(
            model_name='coincidentconstraint',
            name='point2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point2_coincidentconstraint', to='references.referencepoint'),
        ),
    ]
