# Generated by Django 5.2.5 on 2025-11-13 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0015_alter_coincidentconstraint_point1_and_more'),
        ('references', '0005_alter_referenceline_point1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coincidentconstraint',
            name='point1',
        ),
        migrations.RemoveField(
            model_name='coincidentconstraint',
            name='point2',
        ),
        migrations.AddField(
            model_name='coincidentconstraint',
            name='reference1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reference1_coincidentconstraint', to='references.reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coincidentconstraint',
            name='reference2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reference2_coincidentconstraint', to='references.reference'),
            preserve_default=False,
        ),
    ]
