# Generated by Django 5.2.5 on 2025-11-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constraints', '0016_remove_coincidentconstraint_point1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constraint',
            name='is_explicit',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
