# Generated by Django 5.2.5 on 2025-11-08 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0005_remove_pointtemplate_component_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assembly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_assemblycomponent', to='assemblies.assembly')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_assemblycomponent', to='components.component')),
            ],
        ),
        migrations.CreateModel(
            name='AssemblyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed', models.BooleanField(default='false')),
                ('label', models.CharField(max_length=32)),
                ('x', models.FloatField(help_text='[mm]')),
                ('y', models.FloatField(help_text='[mm]')),
                ('units', models.CharField(choices=[('mm', 'mm'), ('inches', 'inches')], default='mm', max_length=6)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_assemblypoint', to='assemblies.assembly')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_assemblypoint', to='assemblies.assemblycomponent')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_assemblypoint', to='components.location')),
            ],
        ),
    ]
