# Generated by Django 5.2.5 on 2025-11-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblypoint',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
