# Generated by Django 5.2.5 on 2026-01-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assembly',
            name='solved',
        ),
    ]
