# Generated by Django 5.2.5 on 2025-11-08 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0002_alter_assemblypoint_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblypoint',
            name='assembly',
        ),
    ]
