# Generated by Django 5.2.5 on 2025-11-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0003_remove_assemblypoint_assembly'),
        ('components', '0005_remove_pointtemplate_component_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblypoint',
            name='units',
        ),
        migrations.AddField(
            model_name='assemblycomponent',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assemblycomponent',
            name='pivot',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pivot_assemblycomponent', to='components.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assemblycomponent',
            name='rotation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assemblycomponent',
            name='x_translation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assemblycomponent',
            name='y_translation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assemblypoint',
            name='x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assemblypoint',
            name='y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
