# Generated by Django 5.2.5 on 2025-11-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0004_remove_assemblypoint_units_assemblycomponent_fixed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assembly',
            options={'verbose_name_plural': 'Assemblies'},
        ),
    ]
