# Generated by Django 5.2.5 on 2025-11-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0005_alter_assembly_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblypoint',
            name='fixed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
