# Generated by Django 5.2.5 on 2025-11-08 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0006_alter_assemblypoint_fixed'),
        ('components', '0005_remove_pointtemplate_component_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblycomponent',
            name='pivot',
        ),
        migrations.AddField(
            model_name='assemblycomponent',
            name='pivot_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pivotpoint_assemblycomponent', to='components.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assemblycomponent',
            name='translation_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translationpoint_assemblycomponent', to='components.location'),
            preserve_default=False,
        ),
    ]
