# Generated by Django 5.2.5 on 2025-11-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0007_remove_assemblycomponent_pivot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='solved',
            field=models.BooleanField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
