# Generated by Django 5.2.5 on 2025-11-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0008_assembly_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='solved',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
