# Generated by Django 5.2.5 on 2025-11-10 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0009_alter_assembly_solved'),
        ('components', '0006_alter_location_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblycomponent',
            name='pivot_point',
        ),
        migrations.RemoveField(
            model_name='assemblycomponent',
            name='translation_point',
        ),
        migrations.AddField(
            model_name='assemblycomponent',
            name='transformation_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transformationpoint_assemblycomponent', to='components.location'),
            preserve_default=False,
        ),
    ]
