# Generated by Django 5.2.5 on 2025-11-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0010_remove_assemblycomponent_pivot_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='status',
            field=models.CharField(choices=[('Not constrained', 'Not constrained'), ('Partially constrained', 'Partially constrained'), ('Fully constrained', 'Fully constrained')], default=1, editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
