# Generated by Django 5.2.5 on 2025-11-11 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0011_assembly_status'),
        ('constraints', '0015_alter_coincidentconstraint_point1_and_more'),
        ('references', '0005_alter_referenceline_point1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssemblyPoint',
        ),
    ]
