# Generated by Django 5.2.5 on 2025-11-16 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0012_delete_assemblypoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblycomponent',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='assemblycomponent',
            name='transformation_point',
        ),
        migrations.RemoveField(
            model_name='assemblycomponent',
            name='x_translation',
        ),
        migrations.RemoveField(
            model_name='assemblycomponent',
            name='y_translation',
        ),
    ]
