# Generated by Django 5.2.5 on 2025-11-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0013_remove_assemblycomponent_rotation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assemblycomponent',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='assemblycomponent',
            name='component',
        ),
    ]
