# Generated by Django 5.2.5 on 2025-11-16 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0014_remove_assemblycomponent_assembly_and_more'),
        ('references', '0010_alter_referencecomponentpoint_location_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssemblyComponent',
        ),
    ]
