# Generated by Django 5.2.5 on 2025-11-08 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_component', to='components.componenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='PointTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('order', models.PositiveIntegerField()),
                ('component_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componenttemplate_pointtemplate', to='components.componenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='[mm]')),
                ('y', models.FloatField(help_text='[mm]')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_componentpoint', to='components.component')),
                ('point_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pointtemplate_componentpoint', to='components.pointtemplate')),
            ],
        ),
    ]
