# Generated by Django 5.2.5 on 2025-11-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentpoint',
            name='units',
            field=models.CharField(choices=[('mm', 'mm'), ('inches', 'inches')], default='mm', max_length=6),
        ),
        migrations.AlterField(
            model_name='pointtemplate',
            name='order',
            field=models.PositiveIntegerField(help_text='Adjacent points are affected by order.'),
        ),
    ]
