# Generated by Django 5.2.5 on 2025-11-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_componentpoint_units_alter_pointtemplate_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='number',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
