# Generated by Django 5.2.5 on 2025-11-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_component_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointtemplate',
            name='type',
            field=models.CharField(choices=[('Geometrical', 'Geometrical'), ('Observational', 'Observational')], default='geometrical', max_length=13),
        ),
        migrations.AlterField(
            model_name='pointtemplate',
            name='order',
            field=models.PositiveIntegerField(help_text="Adjusting the order will only change the plot's contour."),
        ),
    ]
