# Generated by Django 5.2.5 on 2025-11-08 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_pointtemplate_type_alter_pointtemplate_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointtemplate',
            name='component_template',
        ),
        migrations.RenameModel(
            old_name='ComponentTemplate',
            new_name='Template',
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=32)),
                ('type', models.CharField(choices=[('Geometrical', 'Geometrical'), ('Observational', 'Observational')], default='geometrical', max_length=13)),
                ('order', models.PositiveIntegerField(help_text="Adjusting the order will affect the component's contour. Match point adjacency with order.")),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_point', to='components.template')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(help_text='[mm]')),
                ('y', models.FloatField(help_text='[mm]')),
                ('units', models.CharField(choices=[('mm', 'mm'), ('inches', 'inches')], default='mm', max_length=6)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_pointdata', to='components.component')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_location', to='components.point')),
            ],
        ),
        migrations.DeleteModel(
            name='ComponentPoint',
        ),
        migrations.DeleteModel(
            name='PointTemplate',
        ),
    ]
