# Generated by Django 5.2.5 on 2025-11-10 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0005_remove_pointtemplate_component_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_location', to='components.component'),
        ),
    ]
