# Generated by Django 5.2.5 on 2025-11-16 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_alter_location_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='mass',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
