# Generated by Django 5.2.5 on 2025-11-09 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assemblies', '0009_alter_assembly_solved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('fixed', models.BooleanField(default=False, editable=False)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_referenceline', to='assemblies.assembly')),
                ('point1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point1_referenceline', to='assemblies.assemblypoint')),
                ('point2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point2_referenceline', to='assemblies.assemblypoint')),
            ],
        ),
    ]
