# Generated by Django 5.2.5 on 2025-11-29 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assemblies', '0001_initial'),
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(editable=False, max_length=50)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Fixed', 'Fixed'), ('Random', 'Random'), ('Partially constrained', 'Partially constrained'), ('Fully defined', 'Fully defined')], default='Random', editable=False, max_length=21)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_reference', to='assemblies.assembly')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceLine',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='references.reference')),
            ],
            bases=('references.reference',),
        ),
        migrations.CreateModel(
            name='ReferenceComponent',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='references.reference')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_referencecomponent', to='components.component')),
            ],
            bases=('references.reference',),
        ),
        migrations.CreateModel(
            name='ReferenceAngle',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='references.reference')),
                ('line1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line1_referenceangle', to='references.referenceline')),
                ('line2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line2_referenceangle', to='references.referenceline')),
            ],
            bases=('references.reference',),
        ),
        migrations.CreateModel(
            name='ReferencePoint',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='references.reference')),
                ('x_plot', models.FloatField()),
                ('y_plot', models.FloatField()),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_referencepoint', to='references.referencecomponent')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_referencepoint', to='components.location')),
            ],
            bases=('references.reference',),
        ),
        migrations.AddField(
            model_name='referenceline',
            name='point1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point1_referenceline', to='references.referencepoint'),
        ),
        migrations.AddField(
            model_name='referenceline',
            name='point2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point2_referenceline', to='references.referencepoint'),
        ),
    ]
