# Generated by Django 5.2.5 on 2025-11-09 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0009_alter_assembly_solved'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('fixed', models.BooleanField(default=False, editable=False)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_reference', to='assemblies.assembly')),
            ],
        ),
        migrations.RemoveField(
            model_name='referenceline',
            name='assembly',
        ),
        migrations.RemoveField(
            model_name='referenceline',
            name='fixed',
        ),
        migrations.RemoveField(
            model_name='referenceline',
            name='id',
        ),
        migrations.RemoveField(
            model_name='referenceline',
            name='label',
        ),
        migrations.AddField(
            model_name='referenceline',
            name='reference_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='references.reference'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ReferenceAngle',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='references.reference')),
                ('line1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line1_referenceangle', to='references.referenceline')),
                ('line2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line2_referenceangle', to='references.referenceline')),
            ],
            bases=('references.reference',),
        ),
    ]
