# Generated by Django 5.2.5 on 2025-11-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
