# Generated by Django 5.2.5 on 2025-11-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_reference_remove_referenceline_assembly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='type',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
