# Generated by Django 5.2.5 on 2025-11-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0002_reference_hidden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='status',
        ),
        migrations.AddField(
            model_name='reference',
            name='fixed',
            field=models.BooleanField(default=False),
        ),
    ]
