# Generated by Django 5.2.5 on 2025-11-11 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0011_assembly_status'),
        ('components', '0006_alter_location_component'),
        ('references', '0003_alter_reference_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferencePoint',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='references.reference')),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_referencepoint', to='assemblies.assemblycomponent')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_referencepoint', to='components.location')),
            ],
            bases=('references.reference',),
        ),
    ]
