# Generated by Django 5.2.5 on 2025-11-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0003_remove_reference_status_reference_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='hidden',
        ),
        migrations.AddField(
            model_name='reference',
            name='visibility',
            field=models.CharField(choices=[('Shown', 'Shown'), ('Hidden', 'Hidden'), ('Translucent', 'Translucent')], default='Shown', max_length=11),
        ),
    ]
