# Generated by Django 5.2.5 on 2025-11-11 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_referencepoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referenceline',
            name='point1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point1_referenceline', to='references.referencepoint'),
        ),
        migrations.AlterField(
            model_name='referenceline',
            name='point2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point2_referenceline', to='references.referencepoint'),
        ),
    ]
