# Generated by Django 5.2.5 on 2025-12-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0004_remove_reference_hidden_reference_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='fixed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
