# Generated by Django 5.2.5 on 2025-11-15 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_alter_referenceline_point1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='fixed',
            field=models.CharField(choices=[('Fixed', 'Fixed'), ('Random', 'Random'), ('Partially constrained', 'Partially constrained'), ('Fully defined', 'Fully defined')], default='Random', editable=False, max_length=21),
        ),
    ]
