# Generated by Django 5.2.5 on 2025-12-06 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0005_alter_reference_fixed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='visibility',
        ),
    ]
