# Generated by Django 5.2.5 on 2026-01-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_remove_reference_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reference',
            name='fixed',
        ),
        migrations.AddField(
            model_name='referencepoint',
            name='dof',
            field=models.PositiveIntegerField(default=2, editable=False),
        ),
    ]
