# Generated by Django 5.2.5 on 2025-11-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0006_alter_reference_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencepoint',
            name='x',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referencepoint',
            name='y',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
