# Generated by Django 5.2.5 on 2025-11-15 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_alter_referencepoint_x_alter_referencepoint_y'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='fixed',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='referencepoint',
            old_name='x',
            new_name='x_plot',
        ),
        migrations.RenameField(
            model_name='referencepoint',
            old_name='y',
            new_name='y_plot',
        ),
    ]
