# Generated by Django 5.2.5 on 2026-01-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0007_remove_reference_fixed_referencepoint_dof'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencecomponent',
            name='dof',
            field=models.PositiveIntegerField(default=3, editable=False),
        ),
    ]
