# Generated by Django 5.2.5 on 2025-11-15 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0012_delete_assemblypoint'),
        ('components', '0006_alter_location_component'),
        ('references', '0008_rename_fixed_reference_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referencepoint',
            name='component',
        ),
        migrations.RemoveField(
            model_name='referencepoint',
            name='location',
        ),
        migrations.CreateModel(
            name='ReferenceComponentPoint',
            fields=[
                ('referencepoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='references.referencepoint')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_referencepoint', to='assemblies.assemblycomponent')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_referencepoint', to='components.location')),
            ],
            bases=('references.referencepoint',),
        ),
    ]
