# Generated by Django 5.2.5 on 2025-11-16 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0014_remove_assemblycomponent_assembly_and_more'),
        ('components', '0007_component_mass'),
        ('references', '0009_remove_referencepoint_component_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencecomponentpoint',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_referencecomponentpoint', to='components.location'),
        ),
        migrations.CreateModel(
            name='ReferenceComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed', models.BooleanField(default=False)),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_referencecomponent', to='assemblies.assembly')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_referencecomponent', to='components.component')),
            ],
        ),
        migrations.AlterField(
            model_name='referencecomponentpoint',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_referencecomponentpoint', to='references.referencecomponent'),
        ),
    ]
